### ISSUE TITLE
Disk free space widget

### ISSUE THREAD

**Issue by khorolets** [iglance/iGlance#121]
Hi! First of all, I love your project, using it on every mac I have. Appreciate your work!

**Is your feature request related to a problem? Please describe.**
The app I was using before iGlance is iStatMenus (if I'm not mistaken). There was nice widget (idk what term you use for that CPU, RAM, Network things on a bar). There were two letters F (fo Free space left on the disk) and U (for used place obviously). 
That thing was really useful for me. Would be happy to have such thing in iGlance as well.

**Describe the solution you'd like**
Want to see Free and Used disk space in GB

`**Describe alternatives you've considered**
iStatMenus

**Additional context**
Here is the screenshot from iStatMenus
![image](https://user-images.githubusercontent.com/3235740/78381844-9dde4300-75de-11ea-9916-4232336c5b35.png)

And I can't stop thanking you for your brilliant app!

**Comment by D0miH** [comment]
Hey @khorolets,

thanks for your feedback. This is a good idea!
However I think I have to postpone to implement this feature until after version 2.1 of the app is released. I will add it to the feature list for version 2.2.

However, if you really need this feature and want work on it feel free to do so and open a PR :)

**Comment by khorolets** [comment]
@D0miH oh, since you have time and patience to wait, I’d like to try. Swift is my very new passion. Would appreciate if you point me some places and other stuff I might need to implement it.

**Comment by D0miH** [comment]
Glad to hear you want to try it!👍🏼

After a quick google search I think those two sites could help you reading the disk size:
https://eclecticlight.co/2018/02/05/scripting-in-swift-checking-free-disk-space/
https://developer.apple.com/documentation/foundation/urlresourcekey/checking_volume_storage_capacity

As for integrating it into the app I think the main steps you have to do are the following:
- implement a function that can read the free and total disk space (you can just create a new function for this in the "DiskInfo" class)
- create a new "Disk" sidebar item with a disk view in for the main view (I hope you know what I mean)
- then you want to create a new disk menu bar item which inherits from the "MenuBarItem" class
- Save the user settings of the disk menu bar item

If you have any problems understanding the code or get stuck don't hesitate to ask here!😁

Happy hacking💻!

**Comment by khorolets** [comment]
Hi @D0miH 

Sorry for the delay (the work, you know)

I need some help. What've I done already:

* Add function to get necessary values about the disk usage into `/SystemInfo/DiskInfo.swift`
* Create `DiskUsageMenuBarItem: MenuBarItem` that is displaying everything properly

I've added new menu bar item [here](https://github.com/iglance/iGlance/blob/master/iGlance/iGlance/iGlance/MenuBarItems/MenuBarItemManager.swift#L41).

And now I have understanding issue with how to implement settings for user about this new bar item and other stuff. I guess it's about your 

> create a new "Disk" sidebar item with a disk view in for the main view (I hope you know what I mean)

So perhaps I don't know what you mean. I'd appreciate if you can explain details a bit more for me to finish the feature :)

Thank you!

**Comment by D0miH** [comment]
Hey @khorolets,

nice to hear you made progress!

To present the user a settings view within the iGlance window you basically have to do 3 things:
1. Adding a new view controller to the main storyboard that is linked to your `DiskViewController.swift` that you have to create in the folder `/MainWindow/MainViews/`. The view controller is called `DiskViewController` in the following, while the swift file for the view controller on the storyboard is called `DiskViewController.swift`. The `DiskViewController`-class in the `DiskViewController.swift` should inherit from the `MainViewViewController`-class to get the correct transparent background according to the current theme. Don't forget to set the "Identity" of the view controller in the identity inspector. To create a new segue from the battery view controller to the newly created disk view controller on the storyboard, you have to hold control and drag from the "BatteryViewController" to the "DiskViewController" in the outline view of the storyboard on the left side and choose "custom". The newly created segue has to reference the class "SegueBetweenEmbedded" in the attribute inspector. For better debugging you should also give the segue a name.
2. The second step is to implement the settings in the `DiskViewController` on the main storyboard and the corresponding `DiskViewController.swift`. Keep in mind that the settings have to be saved using the `UserSettings`-class in `UserSettings.swift`.
3. The last step to make the `DiskViewController` visible in the app, is to create a clickable sidebar button that, when clicked, displays the settings for the disk (what I mean by sidebar button is marked in the picture). To implement this, you can copy  an existing sidebar button and paste it at the bottom of the stacked buttons on the main storyboard and exchange the icon and the title. Because we have to reference this button from the app it is important that you set the "Identity" in the identity inspector. Now to make the button clickable we have to reference it from the code. In `/MainWindow/Sidebar/SidebarViewController.swift` you can see an array containing all the `SidebarButtonIDs`. Here you have to add an entry for the disk sidebar button which includes the view "Identity" of the sidebar button view, the "Identity" of the "DiskViewController" on the main storyboard and the name of the icon that is going to be used on the sidebar button.

In theory the settings should be displayed then. I hope I didn't forget something😅

If you still have questions feel free to ask again. I am happy for every contribution! :)

With "sidebar button" I mean the button that is marked in the picture below:
<img width="292" alt="Screenshot 2020-04-20 at 16 54 45" src="https://user-images.githubusercontent.com/36657497/79776077-78b73780-8335-11ea-8b01-baf74ef1a72d.png">
