### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by rlyttle** [iglance/iGlance#177]
**Describe the bug🐛**
Memory utilisation seems extremely high (1GB+) as seen from Mac Activity Monitor. Restarting iglance caused it to reduce to 18MB, constantly increasing

**To Reproduce**
None - running in system background, uptime 5 days

**Expected behavior**
Probably shouldn't be so high :)

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/19949843/81506050-b7fcf680-92eb-11ea-9973-0debaafe1b4b.png)

**Desktop (please complete the following information):**

- MacOS Version: 10.15.4
- Version of the app: 2.0.8

**Log**
Attached, but may not demonstrate issue as it's likely due to long-running process
[io.github.iglance.iGlance 2020-05-10--17-28-06-415.log](https://github.com/iglance/iGlance/files/4606305/io.github.iglance.iGlance.2020-05-10--17-28-06-415.log)

**Comment by D0miH** [comment]
Hi @rlyttle,

thanks for reporting the bug. iGlance shouldn't hog this much memory.
However, increasing memory usage is intended since we are caching the bar graph images that are drawn in the menu bar in order to not having to redraw them every time. My assumption is that something went wrong in the caching process. 

Did you switch the macOS theme from dark to light or the other way around? This might cause this bug. 
Please export the app settings under `File`>`Export settings...` and upload them here. This would help me to reproduce the bug.

**Comment by rlyttle** [comment]
Settings file:
[settings.json.txt](https://github.com/iglance/iGlance/files/4608540/settings.json.txt)

I'm using the dark mac OS theme, not sure if I switched before or after installation. Let me know if there's anything else you need!

**Comment by rrodrigues** [comment]
Hi,
I also have noticed this.
I have restarted the app and didn't change anything since and the memory is increasing.

[settings.json.txt](https://github.com/iglance/iGlance/files/4628509/settings.json.txt)

**Comment by D0miH** [comment]
Ok, I found the issue.
Something went wrong while caching the images of the memory bar graph.

Thanks for your help guys!👍🏼
