### ISSUE TITLE
iGlance wont open (automatically on boot or manually by clicking it)

### ISSUE THREAD

**Issue by vinayns** [iglance/iGlance#179]
Hello,
I am having an issue with iGlance not working on my laptop (hackintosh).
It was working for almost a month or two until around 3 weeks ago. 
I assumed initially it was a bug which is not auto opening upon boot.
But when I try to run it through launchpad, nothing happens. 
I tried going to the applications folder and opening it by right clicking but nothing.
I tried it on Mojave 10.14.3 and 10.14.6 but nothing.

Kindly let me know if I can share any bug report or logs. 
Where can I find it?
Thank you.

**Comment by D0miH** [comment]
Hi @vinayns,

because at launch the app tries to read the System Management Controller (SMC) and other system related info I suppose that something is not working properly on a hackintosh. 

You can find logs of the app itself in the folder `~/Library/Logs/iGlance` and logs for automatically launching the app on start in the folder `~/Library/Logs/iGlanceLauncher`. It might be the case that the bug is only appearing in the app so there might be no `~/Library/Logs/iGlanceLauncher` folder.

You can find crash reports by opening the `Console.app` and clicking on `Crash Reports` in the left sidebar. If iGlance crashed there should be some crash reports with the corresponding date.

You can upload those files here and I will try to fix the bug:)

**Comment by vinayns** [comment]
Hi @D0miH 
please find attached the two log files I could find through the Console app..
Hope this helps.. viel glück :)

[io.github.iglance.iGlance 2020-05-11--16-35-19-436.log](https://github.com/iglance/iGlance/files/4620834/io.github.iglance.iGlance.2020-05-11--16-35-19-436.log)
[io.github.iglance.iGlance 2020-05-12--17-32-40-178.log](https://github.com/iglance/iGlance/files/4620835/io.github.iglance.iGlance.2020-05-12--17-32-40-178.log)

**Comment by D0miH** [comment]
Thanks👍🏼. I suppose you took those files from the Console.app under `Log Reports`?
There was no crash report in the Console.app under `Crash Reports`?

**Comment by vinayns** [comment]
Yep, these were in the 'Log Reports'.. 
I've dug out some crash reports, but they were in the 'User Reports' section.. 
I couldn't find a 'Crash Report' folder..

Please find the attached ZIP of same..

[iGlance Crash Report.zip](https://github.com/iglance/iGlance/files/4629293/iGlance.Crash.Report.zip)

**Comment by D0miH** [comment]
Ok @vinayns,
I think I found the bug that caused this issue. Apparently on a hackintosh iGlance is not able to read information about the battery. 
Therefore, I implemented a bug fix that should also fix #96.

The fix will be probably published in the next few days. :)

**Comment by ChillarAnand** [comment]
Is this issue fixed on 2.0.9? Autostart on boot is not working for me on 2.0.9.

**Comment by D0miH** [comment]
I thought so that autostart on boot was fixed. 
@ChillarAnand But the app is opening when you double click it right? Because @vinayns had the problem that the app wouldn't start even when he tried to manually open it.

**Comment by ChillarAnand** [comment]
On double click it is working. @D0miH 

I have been restarting Mac multiple times lately and starting iGlance manually every time is bit tedious.

**Comment by D0miH** [comment]
Hmm this is very strange. I just tested it on my mac (Macbook pro 2018) and on another mac (Macbook pro 2019) and on both it worked. For version 2.0.9 I switched to an external library that handles the autostart on boot that is used by many other apps. So I really have no idea why it is not working.
I suppose it has something to do with your machine. You could try the following.
- disable "Autostart on boot" and close the app
- remove the app from the computer (be sure to clear the bin since that can cause problems with autostart)
- remove **ALL** settings of the current and previous versions of the app. To do list all settings files of all versions open the terminal and type `ls ~/Library/Preferences/ | grep iglance`. You can then remove the files one by one by entering the command `rm ~/Library/Preferences/<name of the settings file>`.
- after you removed all the settings files restart your mac
- reinstall iGlance

I hope this helps.

**Comment by ChillarAnand** [comment]
I think the issue was happening due to multiple plist files. 

```sh
$ ls ~/Library/Preferences/ | grep iglance              
io.github.iglance.iGlance.plist io.iglance.iglance.plist
```

After cleaning up the files and reinstalling, there is only 1 plist file and it seems to be working fine. 

```
$ ls ~/Library/Preferences/ | grep iglance
io.github.iglance.iGlance.plist
```

Thanks for the suggestions. @D0miH

**Comment by D0miH** [comment]
Nice! Happy to hear that you resolved the issue :)

**Comment by ChillarAnand** [comment]
Any idea why `io.iglance.iglance.plist` file got created? Just wondering how the problem began.

**Comment by D0miH** [comment]
When version 2.0 was released we changed the app bundle identifier. I didn't expect the old .plist file to interfere with the new version of the app. Sorry for the inconvenience.
