### ISSUE TITLE
Interactive battery icon

### ISSUE THREAD

**Issue by Darktortue** [iglance/iGlance#217]
It would be great if the battery icon was interactive. By interactive I mean it gets empty if we don't have battery etc...
I use the percentage symbol which is something i like but an interactive icon would be really cool.

**Comment by D0miH** [comment]
Hey,
do you mean the battery icon in the menu bar? In theory the battery icon should indicate the current charge of the battery (see picture).

<img width="50" alt="Screenshot 2020-10-01 at 11 17 53" src="https://user-images.githubusercontent.com/36657497/94791326-c1d8e080-03d7-11eb-881c-c9795c677051.png">


Is this not working on your machine?

**Comment by Darktortue** [comment]
Hello, yes I'm talking about this.
For me the icon doesn't indicate the current charge of the battery. Must be a bug then...
<img width="55" alt="Capture d’écran 2020-10-01 à 11 20 58" src="https://user-images.githubusercontent.com/11302315/94791696-504d6200-03d8-11eb-86fe-f6cbe8fd9b32.png">

**Comment by D0miH** [comment]
Oh, this is a bug indeed. Could you open a new issue and fill in the bug template? This would give a bit more info to investigate the issue.

**Comment by Darktortue** [comment]
Actually i just restarted the app because I wanted to active advanced logging and then it worked correctly. Do you still want the logs ? Because I'm not sure I can reproduce it

**Comment by D0miH** [comment]
Great to hear that. No, if the issue is resolved I don't think the logs will be useful. Hopefully it was just a one-time glitch. 
If you want you can leave advanced logging activated and see if the issue reappears. Advanced logging will not influence the performance of the app or the system and there only the last 7 log files are kept. If the issue reappears you can export the log file by opening the app and clicking on `Diagnostics > Save Logfile...`.
