### ISSUE TITLE
Dark mode UI fixes

### ISSUE THREAD

**Issue by edwardbattistini** [iglance/iGlance#228]
**Describe the bug🐛**
- The titlebar is not switching to dark when using dark mode at OS level
- Settings button is not switching to light when using dark mode at OS level

**To Reproduce**

- Set dark mode on OSx
- Display iGlance 

**Expected behavior**
- Title bar should be dark and title light
- Setting button should be light

**Screenshots (Optional)**
<img width="942" alt="Screenshot 2020-10-06 at 16 48 24" src="https://user-images.githubusercontent.com/6288298/95225828-1e7f3580-07f4-11eb-88d3-b40e75dd3b7d.png">

**Desktop (please complete the following information):**

- MacOS Version: Big Sure Public beta 3
- Version of the app: 2.1

**Log**
Please activate `Advanced Logging` in the settings, restart the app and perform the steps to reproduce the bug.
After the bug occurred, please open the iGlance window and in the app menu at the top left of the menu bar click on `Diagnostics > Save Logfile...`.
Save the logfile somewhere and upload it here by dragging the file into the textfield.

**Comment by edwardbattistini** [comment]
A reboot of the app actually fixes the issue...

**Comment by D0miH** [comment]
Yeah I saw [this](https://github.com/ruiaureliano/macOS-Appearance/pull/2) PR and tested it during development. But apparently the app is running just slow enough in debug mode such that this issue is not appearing during development. I think adding a short delay before changing the theme of the app will fix this (hopefully).
