### ISSUE TITLE
Is SystemX plagiarizing you?

### ISSUE THREAD

**Issue by xzsss** [iglance/iGlance#31]
This app is SO GOOD! 
I found a  software in appstore called SystemX and it is charge
but i got the update push today  and the link is your git
only name and picture  is diffferent
so,Is SystemX plagiarizing you?

**Comment by maesa** [comment]
Holy****, the developer "zhurong li" straight copy and rename few string then sell it in app store

/cc @D0miH @Moneypulation

**Comment by xzsss** [comment]
pls do something to this  
, this software has been in top 5 softwares in appstore(China)
Hope  to add more language like  ch jp  then put iGlance in appstore
we d like to buy it
(i can give some chinese translate support)

**Comment by wx-Yao** [comment]
Confirmed this app in Australia app store. I'm thinking about reporting the developer to Apple.

**Comment by TheTechRobo** [comment]
Yeah, it's in the Canadian store 😢

**Comment by TheTechRobo** [comment]
@D0miH you need to see this

**Comment by D0miH** [comment]
Hey guys,
first of all thanks for the kind words :)
Unfortunately he has the right to sell our app since it is licensed under the MIT license. This allows anybody to redistribute, edit and also sell our app.

I am currently in the process of rewriting the whole app in electron for a better user interface and to include automatic updates within the app (you may know this from some electron apps already e.g. GitHub-Desktop, VSCode).
My plan is to publish this app under my github account for free and eventually sell it in the mac app store if you want to buy it.
