### ISSUE TITLE
Net speed not show in Catalina OS X

### ISSUE THREAD

**Issue by mohsinalimat** [iglance/iGlance#47]
Hello,

Net speed not show in Catalina OS X with you latest version app dmg

![Screenshot 2019-10-25 at 10 54 32 AM](https://user-images.githubusercontent.com/973676/67545223-ffd47b80-f715-11e9-846e-af25806c2cea.png)

**Comment by schwingi000** [comment]
I can confirm this issue and provide some additional information:
With Catalina 10.15.1 (19B88) on an Macbook Pro from Mid 2014 and iGlance 1.4.1 everything is working fine except the network usage. If i'm deactivating my wifi-adapter it's ok (but useless), otherwise it seems as iglance is trying pretty hard to get some informations, that's causing a lot of waiting time.

Hope this is some useful information to you guys!

**Comment by D0miH** [comment]
Hey guys,

thanks for the detailed bug description. 
Currently the network speed is retrieved by using the `netstat` command. However we are currently only measuring the network speed of interface `en0`. 

My assumption is that your mac is using a different interface. 
One possible solution would be to provide a list with possible interfaces of the machine in a drop down list. The user could then select the correct interface. This might not be ideal but should work in most cases.

At the moment I am very busy and I will try to get this done when I have some time. However if someone of you want to implement this feel free to create a PR. Just leave a message here so everyone knows that you are working on the issue.

Cheers :)

**Comment by GingkathFox** [comment]
I have a Catalina dual-boot on my Air, will see what interface Catalina has defined.

**Comment by D0miH** [comment]
fixed with #61
