### ISSUE TITLE
The app is crashed every time I connect to the VPN

### ISSUE THREAD

**Issue by scor2k** [iglance/iGlance#83]
**Describe the bug**
The app is crashed every time I connect to the VPN if the network usage is on. 

**To Reproduce**
1. Enable network usage option
2. Connect to a VPN 
3. App is crashed

**Expected behavior**
The app should continue working :) 

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3 (19D76)
 - Version of the app: 2.0.0 / 2.0.1 

**Additional context**
[io.github.iglance.iGlance 2020-03-29--08-09-29-962.log](https://github.com/iglance/iGlance/files/4398448/io.github.iglance.iGlance.2020-03-29--08-09-29-962.log)

**Comment by D0miH** [comment]
Hey @scor2k,
thanks for reporting this bug🐛 report. Because it is hard to diagnose this bug without any further information could you please enable 'Advanced Logging' in the settings and then perform the actions that lead to the crash? After activating 'Advanced Logging' you can find the log file under `~/Library/Logs/iGlance`.
You can append the file under `Additional context` when editing your bug report.

Thanks👍🏼

**Comment by scor2k** [comment]
Hi, @D0miH! 

You can find this report attached.

[io.github.iglance.iGlance 2020-03-29--08-09-29-962.log](https://github.com/iglance/iGlance/files/4398448/io.github.iglance.iGlance.2020-03-29--08-09-29-962.log)
