### ISSUE TITLE
Dashboard shows wrong system information

### ISSUE THREAD

**Issue by D0miH** [iglance/iGlance#85]
**Describe the bug**
When opening the app on some machines the system information is not set. Therefore the default values are displayed

**To Reproduce**
1. Open the dashboard

**Expected behavior**
The correct system information of the machine should be displayed

**Screenshots**
As you can see the system information on this Macbook Pro with only 8 GB of RAM and a disk size of 256 GB is not correct.
![Bildschirmfoto 2020-03-29 um 10 56 40](https://user-images.githubusercontent.com/36657497/77845089-4be78880-71ac-11ea-88b8-0415e4dc2489.jpeg)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.3
 - Version of the app: 2.0.2

**Comment by D0miH** [comment]
Can't reproduce the bug anymore

**Comment by Planktonette** [comment]
I can confirm I encountered the same issue:

![image](https://user-images.githubusercontent.com/5514719/77871382-cd650800-71f8-11ea-9a1b-d40973226560.png)

After restarting the app it finds the correct information.

![image](https://user-images.githubusercontent.com/5514719/77871418-e968a980-71f8-11ea-827b-26bcb6631075.png)

**Comment by D0miH** [comment]
Hey @Planktonette,
thanks for confirming the issue. I will look into it:)

**Comment by tech189** [comment]
I was able to reproduce this too, although it reappeared shortly after restarting the app
<img width="595" alt="Screenshot 2020-03-30 at 11 53 10" src="https://user-images.githubusercontent.com/10728085/77905676-95a0a380-727e-11ea-836d-e08043b61333.png">

**Comment by Metacomet10** [comment]
Still happening on 2.0.3 upon boot, restarting the app does still work to make it report correctly. Not sure if 10.15.4 vs 10.15.3 is a factor.
<img width="1327" alt="Settings and menu bar with all indicators active" src="https://user-images.githubusercontent.com/6789837/78051457-8f6bff00-7332-11ea-9837-396cfc263f04.png">

**Comment by D0miH** [comment]
Hey @Metacomet10,
thanks for your in-depth analysis. I have access to a macbook pro from 2015.
I will try to reproduce this bug and try to fix it.

**Comment by D0miH** [comment]
@Metacomet10,
so I tried to reproduce the bug as you described on a 2015 MacbookPro. But somehow I could not reproduce it. Everytime I restartet the computer the information on the dashboard was correct. 

Can you reproduce the bug with the latest version (v2.0.5) of the iGlance?

**Comment by Metacomet10** [comment]
No, I am not able to reproduce the bug anymore. Still on 10.15.3.

On a separate note, even with the Autostart on Boot box checked, the app is not opening by itself. This has been an issue since 1.4.3 that I didn't notice until now. Though I do also have Malwarebytes, Avast, Dropbox, PIA, Memory Clean 2, AltServer, F.lux, Magnet, and Activity Monitor loading up on boot too..... so, that might affect it lol. Should I create a new issue for this? I couldn't find a previous bug report to reopen.

**Comment by D0miH** [comment]
Ok, thanks for the feedback @Metacomet10. Since the issue is not appearing anymore I will close this issue.
If someone encounters this issue again, feel free to reopen it.

> Should I create a new issue for this? I couldn't find a previous bug report to reopen.
Yeah, it would be good to open a new issue for that. Otherwise it is going to be a bit confusing.

**Comment by khorolets** [comment]
@D0miH I guess this issue should be reopened. 

I have totally wrong info in dashboard on start (2.0.6 installed via GitHub release zip file)

<img width="344" alt="image" src="https://user-images.githubusercontent.com/3235740/79847550-8ff33500-83c8-11ea-9167-b17fa420adc7.png">

RAM has to be 32, Disk should be 2 TB, GPU and CPU is wrong (placeholders I believe).
But it is weird, because on the first dashboard opening I see Disk 128 GB, on the second time 512 GB, so it is changing, but the values are wrong.

Attaching the log (might be a little bit bigger if app that is launched from XCode writes logs to the file as well, sorry)

[io.github.iglance.iGlance 2020-04-20--13-36-55-308 copy.txt](https://github.com/iglance/iGlance/files/4508895/io.github.iglance.iGlance.2020-04-20--13-36-55-308.copy.txt)

Let me know if I can provide any additional info.

**Comment by khorolets** [comment]
Additional info:

Once I've started the app and opened the window I see all the system info correct except the disk space. Then I go to any VC via sidebar (CPU for instance) and back to Dashboard and system info is displaying the placeholder values. Hope this'll help.

**Comment by D0miH** [comment]
> Once I've started the app and opened the window I see all the system info correct except the disk space. Then I go to any VC via sidebar (CPU for instance) and back to Dashboard and system info is displaying the placeholder values. Hope this'll help.
This helps indeed, since now I have an idea what might cause the issue. Thanks! :)
